- App.tsx
- ios/Podfile.lock
- package.json
- screens/Mart.tsx
- yarn.lock
> native-base UI킷 사용 & 편의점 screen POC

- ios/Podfile.lock
- package.json
- screens/Meal.tsx
- yarn.lock
식당 정렬 코드 정리
Basic Modal 구현
식당 정보 크롤링 구현
식당 즐겨찾기 구현 (로컬스토리지)
> Feat/meal 식단 정보 크롤링, 즐겨찾기, modal 기본 구현

- ios/Podfile.lock
- package.json
- screens/Meal.tsx
- yarn.lock
* 지난 PR 리뷰 뒤늦게 좀 반영
* UI 일부 반영
* colors.ts 반영
* 식당 운영 정보 (메뉴 외 정보) 크롤링 로직 구현
* 아워홈 식당 크롤링 로직 구현
* modal UI 일부 반영
<추가>
+ 이승건 리뷰 반영
> feat/meal: edit UI & fetch cafeteria info & fetch ourhome cafeteria & edit modal UI

- screens/Meal.tsx
> 식당 메뉴 및 가격 표기 완료

- App.tsx
- fonts/OFL.txt
- icons/more.svg
- icons/outlink.svg
- ios/snuinfoapp.xcodeproj/project.pbxproj
- ios/snuinfoapp/Info.plist
- react-native.config.js
- ui/theme.ts
모두 분산된 UI를 통일하기 위해 Theme을 만들었습니다.
- 폰트는 Figma와 동일하게 **Noto Sans KR** 폰트를 사용했고 `fonts` 폴더에 모두 넣어놨습니다.
- `yarn react-native link`로 폰트 링킹 해놨습니다.
- `App.tsx` 폴더에 `ui/theme.ts`에서 `theme`을 import 했고 `<NativeBaseProvider theme={theme}>`으로 지정해줬으니 각 페이지마다 따로 import 할 필요 없이 쓰면 됩니다.
- `theme.ts` 파일에서 볼 수 있듯이 메인 화면에 들어가는 요소들을 각 컴포넌트별로 `variant`로 지정해줬습니다.
- 사용하려면 `<Button variant="favoriteOpenPlace">` or `<Text variant="favoriteMenuPrice">` 처럼 사용하면 됩니다.
- `Button`의 경우 `bg`, `borderColor`, `borderWidth`, `rounded`가 지정되어 있어서 `width`, `height`를 지정해줘야 하고
- `Text`의 경우 `color`, `fontSize`, `fontWeight`가 지정되어 있습니다.
- Figma로 디자인 할때 긴 텍스트에 대해 테스트를 안 해서 차이가 좀 있을 것 같은데, 추후 조율해봅시다!
> UI 통일을 위한 Theme 적용

- ios/snuinfoapp/AppDelegate.m
- screens/Meal.tsx
- replaceAll 함수가 ios에서는 멀쩡히 동작하는데 android에서는 에러 발생하길래 split + join 으로 같은 기능 하도록 코드 수정
- 기타 수정 (메뉴 여러개 나올때 220동 식당은 &도+도 아닌 * 사용하길래 그 부분 추가, 이승건 리뷰 반영 등)
> Feat/meal: 안드로이드에서만 발생한 에러 수정 등

- screens/Etcs.tsx
- ui/theme.ts
- 은행/우체국/교보문고 상세페이지 UI 적용
- 모달 내용 적용을 위해 일부 theme 추가
> Etc 상세페이지 UI 적용

- screens/Meal.tsx
- 이승건의 도움으로 typescript error를 많이 고쳤습니다
> fix: ts error

- components/Grid.tsx
- components/List.tsx
- screens/Meal.tsx
- ui/theme.ts
> 카페/편의점/셔틀 UI 작업

- App.tsx
- components/Grid.tsx
- components/List.tsx
> 헤더 css 작은 수정, warn map 에러 안뜨게 하기

- screens/Etcs.tsx
> 외부 링크 뜨게 함

- src/helpers/localStorage.ts
- src/screens/Meal.tsx
- src/ui/theme.ts
- 식당 기본즐찾 (학관) 설정
- 파업 관련 메뉴 표기 개선
- 불필요한 주석 및 콘솔로그 제거
- 9글자 메뉴 표기 개선
- 기타 메뉴 및 가격 표기 개선
> Feat/meal: 기본즐겨찾기 설정, 파업 관련 표기 개선, 기타 텍스트 데이터 정제 로직 개선

- src/components/Grid.tsx
- Grid 여백 로직 개선 및 오류 (마지막 줄) 수정
> Fix/choo - Grid 오류 수정

- src/InitializeData/FetchData.ts
- src/InitializeData/ProcessMealData.ts
- src/InitializeData/RefineMenuText.ts
- src/InitializeData/index.ts
- src/helpers/getTodaysDate.ts
- src/icons/tomorrow.svg
- src/icons/yesterday.svg
- src/screens/Meal.tsx
- tsconfig.json
- 다른날 메뉴 표기 일단 draft로 내일 메뉴 보기만 대충 짜봤는데(a349b02be001d4ace3c05ee3670d6ea83f753f88) 많은 리뷰와 조언 부탁드림. 
- Fetch => ProcessData => App => Meal 로 어케 넘기는게 제일 좋은 방식일지 모르겠어서 일단 여기까지 해두고 내일 더 고민해보겠음
- 앞뒤로 2일 볼 수 있게 했음
- 더 못 볼 때는 그냥 버튼 안보이게. + 대학원 기숙사 (아워홈)는 전혀 다른 로직이라 일단 빼고 해놓음
- 버튼 넘길때 날짜도 같이 바뀌게 해놨음
- 하는김에 메뉴 텍스트 정제하는 로직 옮기는 리팩토링 함
> fix/meal: 두레미담 추가(draft), 예술계 로직 개선, 다음날 메뉴 표기 draft 코드

- android/app/build.gradle
- package.json
- src/ui/theme.ts
- yarn.lock
경량화된 폰트를 사용하여 용량을 줄입니다.
안드로이드에서 사용하지않는 폰트 파일을 지웠습니다.
별도 node_modules 안에서 경로를 수정해 주지 않아도 빌드가 잘 되도록 엔트리 파일을 설정했습니다.
> fix: 용량 줄이기 & 엔트리 파일 설정

- android/app/build.gradle
- src/InitializeData/FetchData.ts
- src/InitializeData/ProcessMealData.ts
- src/InitializeData/RefineMenuText.ts
- src/helpers/convertToKoreanDay.ts
- src/helpers/getNow.ts
- src/helpers/getTodaysDate.ts
- src/screens/Cafe.tsx
- src/screens/Mart.tsx
- src/screens/Meal.tsx
- src/screens/Shuttle.tsx
- src/ui/theme.ts
- tsconfig.json
- meal.tsx에 eslint 반영
- helper로 getNow 추가해서 사용하게 수정
- 현재 미운영인 식당의 다른날 메뉴 볼 때 운영시간 정보가 안나왔는데 나오게 함
- 개발용 코드 (console.log, asyncstorage.clear()) 제거
> meal.tsx 대폭 개선

- src/InitializeData/FetchData.ts
- src/helpers/localStorage.ts
- https://github.com/workasahobby/iSNU/pull/54 여기서 언급된 버그를 고칩니다.
- 캐시된 정보의 형태가 바뀌어서 생긴 문제입니다.
- 고쳐졌는지 확인이 필요합니다. @DoJunggeun
> 로컬 스토리지 이전 버전 호환성 관련 버그 픽스

- android/app/proguard-rules.pro
- src/App.tsx
- src/InitializeData/ProcessMealData.ts
- src/InitializeData/RefineMenuText.ts
- src/InitializeData/index.ts
- src/helpers/convertToKoreanDay.ts
- #64 에서 setItem쪽은 key를 안바꿔서 마저 바꿨습니다
- android crash 문제를 해결했습니다
- android tabbar의 아이콘과 label이 아래쪽으로 쏠리게 바뀌어 있길래, css 수정했습니다
- processMealData에서 contact 정보를 중복으로 받아와서, 그 부분 삭제하였습니다
> Do: fix android crash error, fix android tabbar css, refactor processMealData

- src/screens/Meal.tsx
301동 '교직원 식당만 운영' 글씨 색을 바꿨습니다.
운영중인것처럼 보이기 때문에...
> 301동 '교직원 식당만 운영' 글씨 색을 바꿨습니다.

- android/app/build.gradle
- ios/snuinfoapp.xcodeproj/project.pbxproj
- package.json
- src/InitializeData/ProcessMealData.ts
- src/InitializeData/ProcessOthersData.ts
- src/InitializeData/ProcessVacation.ts
- src/screens/Cafe.tsx
- src/screens/Meal.tsx
- src/screens/Shuttle.tsx
- 식당, 카페, 셔틀 방학 운영정보 반영 (https://github.com/workasahobby/iSNU/pull/73/commits/f0065ebc183ac9ede1f8861ba66b048cd9241028, https://github.com/workasahobby/iSNU/pull/73/commits/0a486e8bb0be080e23cc078edd51f824860b40b3)
- 하는 김에 발견한 일부 오류(https://github.com/workasahobby/iSNU/pull/73/commits/a16cf8aca30873caff7a3c7687aa532f3f305cdd, https://github.com/workasahobby/iSNU/pull/73/commits/fe5e64221a46a2810a95e2f3cb9fb92d08ec9110) 수정
- 셔틀의 경우 1/26부터 또 운영시간이 다른데, 이건 아직 미반영
- 대학원기숙사(아워홈) 저녁메뉴 표기되지 않는 현상 해결 (임시로 대충 해결했으나 리팩토링이 필요할 듯, 추후 진행하겠음)
> 2.1.2. 한번에 합쳤습니다

- android/app/build.gradle
- ios/snuinfoapp.xcodeproj/project.pbxproj
- src/App.tsx
- src/InitializeData/RefineMenuText.ts
- src/helpers/getNow.ts
- src/screens/Etcs.tsx
- 공신 신한은행 없어져서 삭제
- new Date() 대신 getNow()를 사용하도록 코드 수정
- 메뉴 텍스트 파싱 약간 수정
> 2.1.5 코드 일부 수정

- android/app/build.gradle
- ios/snuinfoapp.xcodeproj/project.pbxproj
- src/InitializeData/RefineMenuText.ts
- src/helpers/getNow.ts
- src/screens/Meal.tsx
> 2.1.6 감골식당 메뉴 정보 표기 수정

- android/app/build.gradle
- android/app/src/main/java/com/snuinfoapp/MainActivity.java
- android/build.gradle
- ios/snuinfoapp.xcodeproj/project.pbxproj
- 안드로이드 crash 에러 발생율이 올라가서, 정확한 원인을 찾으려 노력중입니다
- 근데 못찾아서 일단 이것저것 사소한 개선들을 적용해봤습니다
> trying to fix android crash

- android/app/build.gradle
- ios/snuinfoapp.xcodeproj/project.pbxproj
- src/InitializeData/RefineMenuText.ts
- src/helpers/getNow.ts
- src/screens/Meal.tsx
> 2.1.9 두레미담, 301동 메뉴 표기 개선
